spring:
  application:
    name: simi
  datasource:
    url: jdbc:postgresql://140.83.54.143:55342/simi_dev
    username: simi_user
    password: simi240911
    hikari:
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false # Additional native properties to set on the JPA provider.
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**


ai:
  cerebras:
    token: demo-wjtwjdj3fedf4dhkhx2h52j6twxhhfww3c8pmpt4edvd95jx

security:
  access-token:
    expiry-in-milli: 900000
    jwt-secret-key: "583-05823jkl;jlk023'2jdslga,e/kj3oi25902fhkjweh;"
  refresh-token:
    length-byte: 64
    expiry-value: 1
    expiry-unit: DAYS

springdoc:
  use-fqn: true

logging:
  level:
    root: INFO
    p6spy: DEBUG