spring:
  application:
    name: simi
  datasource:
    url: jdbc:postgresql://140.83.54.143:55342/simi_dev
    username: simi_user
    password: simi240911
    hikari:
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false # Additional native properties to set on the JPA provider.
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**


logging:
  level: # 각 package 별로 로깅 레벨을 지정할 수 있다.
    org.hibernate.type.descriptor.sql: trace    # sql의 ? 값을 Parameter로 보여줌.


ai:
  cerebras:
    token: ${CEREBRAS_API_KEY}

security:
  access-token:
    expiry-in-milli: 900000
    jwt-secret-key: "583-05823jkl;jlk023'2jdslga,e/kj3oi25902fhkjweh;"
  refresh-token:
    length-byte: 64
    expiry-value: 1
    expiry-unit: DAYS

springdoc:
  use-fqn: true