apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: sandbox

replicas:
- count: 1
  name: simi-app-deploy
images:
- name: DOCKER_IMAGE_PLACE_HOLDER
  newName: ocid1.containerrepo.oc1.ap-singapore-1.0.axccb0dejqgl.aaaaaaaaq7rtwua332vxhhdin7k72orfu3tapbibeaf7ohindgyutpg4trma
  newTag: sandbox-20240911T115415UTC
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/tolerations
      value: [ { key: "env", value: "sandbox", effect: "NoSchedule", operator: "Equal" } ]
  target:
    kind: Deployment
