apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: sandbox

replicas:
- count: 1
  name: simi-app-deploy
images:
- name: DOCKER_IMAGE_PLACE_HOLDER
  newName: sin.ocir.io/axccb0dejqgl/simi
  newTag: sandbox-20241126T112744UTC
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/tolerations
      value: [ { key: "env", value: "sandbox", effect: "NoSchedule", operator: "Equal" } ]
  target:
    kind: Deployment
